"""Reachable pose commands for the OneRobotics A1 reach task."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, cast

import mujoco
import numpy as np
import torch
from mjlab.entity import Entity
from mjlab.managers.command_manager import CommandTerm, CommandTermCfg
from mjlab.utils.lab_api.math import (
  matrix_from_quat,
  quat_error_magnitude,
  quat_unique,
  subtract_frame_transforms,
)

from onerobotics_a1_mjlab.a1 import A1_END_EFFECTOR_SITE, get_spec

mj = cast(Any, mujoco)

if TYPE_CHECKING:
  from mjlab.envs import ManagerBasedRlEnv
  from mjlab.viewer.debug_visualizer import DebugVisualizer


class ReachablePoseCommand(CommandTerm):
  """Sample joint configurations and use native MuJoCo FK for pose targets."""

  cfg: ReachablePoseCommandCfg

  def __init__(self, cfg: ReachablePoseCommandCfg, env: ManagerBasedRlEnv):
    super().__init__(cfg, env)
    self.robot: Entity = env.scene[cfg.entity_name]

    joint_ids, joint_names = self.robot.find_joints(
      cfg.joint_names,
      preserve_order=True,
    )
    if len(joint_ids) != 7:
      raise ValueError(f"Expected 7 A1 joints, resolved {len(joint_ids)}")
    site_ids, _ = self.robot.find_sites((cfg.site_name,))
    if len(site_ids) != 1:
      raise ValueError(f"Expected one end-effector site, resolved {len(site_ids)}")

    self._joint_ids = torch.tensor(joint_ids, device=self.device, dtype=torch.long)
    self._site_id = site_ids[0]
    self.target_pose_b = torch.zeros(self.num_envs, 7, device=self.device)
    self.target_pose_b[:, 3] = 1.0
    self.target_joint_pos = torch.zeros(
      self.num_envs,
      len(joint_ids),
      device=self.device,
    )

    limits = self.robot.data.joint_pos_limits[0, self._joint_ids]
    center = 0.5 * (limits[:, 0] + limits[:, 1])
    half_range = 0.5 * (limits[:, 1] - limits[:, 0]) * cfg.joint_range_scale
    self._sample_lower = center - half_range
    self._sample_upper = center + half_range

    # Compile one canonical shadow model. Targets are generated by MuJoCo's own
    # kinematics, so this package does not maintain a duplicate A1 FK chain.
    self._fk_model = get_spec().compile()
    self._fk_data = mj.MjData(self._fk_model)
    self._fk_joint_qpos_adr = np.asarray(
      [
        self._fk_model.jnt_qposadr[self._fk_model.joint(name).id]
        for name in joint_names
      ],
      dtype=np.int32,
    )
    self._fk_site_id = self._fk_model.site(cfg.site_name).id

    self.metrics["position_error"] = torch.zeros(
      self.num_envs,
      device=self.device,
    )
    self.metrics["orientation_error"] = torch.zeros(
      self.num_envs,
      device=self.device,
    )

  @property
  def command(self) -> torch.Tensor:
    return self.target_pose_b

  def current_pose_b(self) -> tuple[torch.Tensor, torch.Tensor]:
    """Return the current end-effector pose in the robot base frame."""
    root_pos_w = self.robot.data.root_link_pos_w
    root_quat_w = self.robot.data.root_link_quat_w
    ee_pos_w = self.robot.data.site_pos_w[:, self._site_id]
    ee_quat_w = self.robot.data.site_quat_w[:, self._site_id]
    return subtract_frame_transforms(
      root_pos_w,
      root_quat_w,
      ee_pos_w,
      ee_quat_w,
    )

  def _update_metrics(self) -> None:
    current_pos_b, current_quat_b = self.current_pose_b()
    self.metrics["position_error"] = torch.linalg.vector_norm(
      self.target_pose_b[:, :3] - current_pos_b,
      dim=-1,
    )
    self.metrics["orientation_error"] = quat_error_magnitude(
      self.target_pose_b[:, 3:],
      current_quat_b,
    )

  def _resample_command(self, env_ids: torch.Tensor) -> None:
    count = len(env_ids)
    sampled = self._sample_lower + (
      self._sample_upper - self._sample_lower
    ) * torch.rand((count, len(self._joint_ids)), device=self.device)
    self.target_joint_pos[env_ids] = sampled

    sampled_cpu = sampled.detach().cpu().numpy()
    target_cpu = np.empty((count, 7), dtype=np.float32)
    quat = np.empty(4, dtype=np.float64)
    for index, qpos in enumerate(sampled_cpu):
      mj.mj_resetData(self._fk_model, self._fk_data)
      self._fk_data.qpos[self._fk_joint_qpos_adr] = qpos
      mj.mj_forward(self._fk_model, self._fk_data)
      target_cpu[index, :3] = self._fk_data.site_xpos[self._fk_site_id]
      mj.mju_mat2Quat(quat, self._fk_data.site_xmat[self._fk_site_id])
      target_cpu[index, 3:] = quat

    target = torch.from_numpy(target_cpu).to(self.device)
    target[:, 3:] = quat_unique(target[:, 3:])
    self.target_pose_b[env_ids] = target

  def _update_command(self, env_ids: torch.Tensor | None) -> None:
    del env_ids

  def _debug_vis_impl(self, visualizer: DebugVisualizer) -> None:
    current_pos_b, current_quat_b = self.current_pose_b()
    root_pos_w = self.robot.data.root_link_pos_w
    root_quat_w = self.robot.data.root_link_quat_w

    # Fixed-base A1 uses identity base orientation in the canonical model. Use
    # current world-space EE data for the actual frame and translate FK targets
    # by the environment's base position for the goal frame.
    for env_id in visualizer.get_env_indices(self.num_envs):
      actual_pos = self.robot.data.site_pos_w[env_id, self._site_id].cpu().numpy()
      actual_quat = self.robot.data.site_quat_w[env_id, self._site_id]
      target_pos = (root_pos_w[env_id] + self.target_pose_b[env_id, :3]).cpu().numpy()
      target_quat = self.target_pose_b[env_id, 3:]
      visualizer.add_sphere(
        actual_pos,
        0.012,
        (0.0, 0.8, 1.0, 1.0),
        label=f"a1_ee_{env_id}",
      )
      visualizer.add_sphere(
        target_pos,
        0.015,
        (1.0, 0.5, 0.0, 0.8),
        label=f"a1_goal_{env_id}",
      )
      visualizer.add_frame(
        actual_pos,
        matrix_from_quat(actual_quat).cpu().numpy(),
        scale=0.08,
        label=f"a1_ee_frame_{env_id}",
      )
      visualizer.add_frame(
        target_pos,
        matrix_from_quat(target_quat).cpu().numpy(),
        scale=0.1,
        label=f"a1_goal_frame_{env_id}",
      )

    del current_pos_b, current_quat_b, root_quat_w


@dataclass(kw_only=True)
class ReachablePoseCommandCfg(CommandTermCfg):
  """Configuration for native-MuJoCo reachable A1 pose commands."""

  entity_name: str = "robot"
  site_name: str = A1_END_EFFECTOR_SITE
  joint_names: tuple[str, ...] = (r"joint[1-7]-a1_r",)
  joint_range_scale: float = 0.8

  @dataclass
  class VizCfg:
    target_color: tuple[float, float, float, float] = (1.0, 0.5, 0.0, 0.8)

  viz: VizCfg = field(default_factory=VizCfg)

  def build(self, env: ManagerBasedRlEnv) -> ReachablePoseCommand:
    return ReachablePoseCommand(self, env)
